version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
#    ports:
#      - 27017:27017

  bot:
    image: mikechan/openricerdelhistorybot
    restart: always
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASSWORD: example
      TG_BOT_TOKEN: 847708851:AAFOjM3ArUmSTeSJWL3v4opc95Qna8U-IPw
    ports:
      - 80:5000
    command: bash -c "python /src/main.py && python /src/cronjob.py"
